---
- name: INSTALL METRICBEAT
  hosts: webservers
  become: true
  tasks:
    - name: DOWNLOAD METRICBEAT AND INSTALL METRICBEAT
      apt: 
        deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.14.0-amd64.deb"
        state: present 

    - name: Update setup.kibana in /etc/metricbeat/metricbeat.yml
      replace:
        path: /etc/metricbeat/metricbeat.yml
        regexp: '(\s+)#host: "localhost:5601"(\s+.*)?$'
        replace: '\1host: "10.0.0.4:5601"\2'
        backup: yes

    - name: Update output.elasticsearch in /etc/metricbeat/metricbeat.yml
      replace:
        path: /etc/metricbeat/metricbeat.yml
        regexp: '(\s+)hosts: \["localhost:9200"\](\s+.*)?$'
        replace: '\1hosts: ["10.0.0.4:9200"]\2'
        backup: yes

    - name: ENABLE AND CONFIGURE DOCKER MODULE FOR METRICBEAT
      command: metricbeat modules enable docker

    - name: SETUP METRICBEAT
      command: metricbeat setup

    - name: ENABLE METRICBEAT ON BOOT
      systemd:
        name: metricbeat
        state: started
        enabled: yes

